version: '3.3'

services:

  provider-service:
    image: provider-service:0.1
    volumes:
      - ./log/:/opt/log/
    entrypoint:
      - java
      - -jar
      - /opt/provider-service.jar
    networks:
      - demo

networks:
  demo:
    external:
      name: demo
