version: '3.3'

services:

  provider-service:
    image: provider-service:0.2
    container_name: provider-service
    volumes:
      - ./log/:/opt/log/
    networks:
      - demo

networks:
  demo:
    external:
      name: demo
