version: '3.3'

services:

  consumer-service:
    image: consumer-service:latest
    build: ./consumer-service/
    volumes:
      - ./consumer-service/log/:/opt/log/
    entrypoint:
      - java
      - -jar
      - /opt/consumer-service.jar
    networks:
      - demo

  provider-service:
    image: provider-service:latest
    build: ./provider-service/
    volumes:
      - ./provider-service/log/:/opt/log/
    entrypoint:
      - java
      - -jar
      - /opt/provider-service.jar
    networks:
      - demo

networks:
  demo:
    external:
      name: demo

