version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.0
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - elk
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch.data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.4.0
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logstash/patterns:/usr/share/logstash/patterns:ro

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.4.0
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elk
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
  
#  apm:
#    image: docker.elastic.co/apm/apm-server-oss:7.4.0
#    volumes:
#      - ./apm/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
#    networks:
#      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.4.0
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    networks:
      - elk
    volumes:
      - ./provider-service/log:/data/provider-service/log:ro
      - ./consumer-service/log:/data/consumer-service/log:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - filebeat.data:/usr/share/filebeat/data

  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer.data:/data

networks:
  elk:
    external:
      name: elk

volumes:
  elasticsearch.data:
  filebeat.data:
  portainer.data:
