version: '3.3'

services:

  consumer-service:
    image: consumer-service:0.2
    container_name: consumer-service
    volumes:
      - ./log/:/opt/log/
    networks:
      - demo

networks:
  demo:
    external:
      name: demo

